name: Compile Documents and Release

permissions:
  contents: write
  discussions: write

on:
  push:
    branches: [ main ]

env:
  SEMVERBOT_VERSION: "1.0.0"

jobs:
  build_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up sbot path
        run: |
          mkdir bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-extra

      - name: Install semverbot
        run: |
          curl -o bin/sbot -L https://github.com/restechnica/semverbot/releases/download/v$SEMVERBOT_VERSION/sbot-linux-amd64
          chmod +x bin/sbot

      - name: Update version
        run: |
          sbot update version
          current_version="$(sbot get version)"
          release_version="$(sbot predict version -m patch)"
          
          echo "CURRENT_VERSION=v${current_version}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=v${release_version}" >> $GITHUB_ENV
          
          echo "current version: v${current_version}"
          echo "next version: v${release_version}"

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: ./
          root_file: main.tex
          args: '-jobname=nigerian_business_insiders_playbook'
          latexmk_use_xelatex: true

      - name: Convert to EPUB
        run: |
          # Create a temporary markdown file from LaTeX
          pandoc -f latex -t markdown main.tex -o temp.md
          
          # Convert markdown to EPUB with metadata
          pandoc temp.md -o nigerian_business_insiders_playbook.epub \
            --metadata title="The Nigerian Business Insider's Playbook" \
            --metadata subtitle="The Underground Guide to Launching and Scaling Successful Ventures in Africa's Hottest Market" \
            --metadata author="Dele Omotosho" \
            --metadata date="$(date +%Y)" \
            --metadata language="en-US" \
            --metadata publisher="Counseal" \
            --metadata description="How Smart Entrepreneurs Enter, Succeed, and Thrive in Nigeria's Multi-Billion Dollar Markets - Even Without Local Connections or Previous African Business Experience" \
            --toc --toc-depth=3 \
            --epub-cover-image=figures/book-cover.png \
            --css=epub.css

      - name: Generate Changelog
        run: |
          if git rev-parse ${{ env.CURRENT_VERSION }} >/dev/null 2>&1; then
            git log ${{ env.CURRENT_VERSION }}..${{ env.RELEASE_VERSION }} --pretty=%s --first-parent > ${{ github.workspace }}-CHANGELOG.txt
          else
            git log --pretty=%s --first-parent > ${{ github.workspace }}-CHANGELOG.txt
          fi
        continue-on-error: true

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Delete existing tag if present
        run: |
          git tag -d ${{ env.RELEASE_VERSION }} || true
          git push origin :refs/tags/${{ env.RELEASE_VERSION }} || true
        continue-on-error: true

      - name: Create and push new tag
        run: |
          git tag ${{ env.RELEASE_VERSION }}
          git push origin ${{ env.RELEASE_VERSION }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          bodyFile: ${{ github.workspace }}-CHANGELOG.txt
          artifacts: "nigerian_business_insiders_playbook.pdf,nigerian_business_insiders_playbook.epub"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true

#      - name: Notify Beta Readers
#        uses: fjogeleit/http-request-action@v1
#        with:
#          url: 'https://n8n.viz.li/webhook/4cbf803f-42df-4bd1-9eac-898a5435907d'
#          method: 'POST'
#          customHeaders: '{"Content-Type": "application/json"}'
#          data: |
#            {
#              "releaseURL": "https://github.com/authwit/book-NigerianBizOpsBlueprint/releases/tag/${{ env.RELEASE_VERSION }}",
#              "version": "${{ env.RELEASE_VERSION }}",
#              "pdfURL": "https://github.com/authwit/book-NigerianBizOpsBlueprint/releases/download/${{ env.RELEASE_VERSION }}/nigerian_business_insiders_playbook.pdf",
#              "epubURL": "https://github.com/authwit/book-NigerianBizOpsBlueprint/releases/download/${{ env.RELEASE_VERSION }}/nigerian_business_insiders_playbook.epub"
#            }