name: Compile Latex and Release PDF

on:
  push:
    branches: [ main ]

env:
  SEMVERBOT_VERSION: "1.0.0"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # This ensures all tags are fetched

      - name: set up sbot path
        run: |
          mkdir bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: install semverbot
        run: |
          curl -o bin/sbot -L https://github.com/restechnica/semverbot/releases/download/v$SEMVERBOT_VERSION/sbot-linux-amd64
          chmod +x bin/sbot

      - name: update version
        run: |
          sbot update version
          current_version="$(sbot get version)"
          release_version="$(sbot predict version -m patch)"
          
          echo "CURRENT_VERSION=v${current_version}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=v${release_version}" >> $GITHUB_ENV
          
          echo "current version: v${current_version}"
          echo "next version: v${release_version}"

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: ./
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Generate Changelog
        run: git log ${{ env.CURRENT_VERSION }}..${{ env.RELEASE_VERSION }} --pretty=%s --first-parent > ${{ github.workspace }}-CHANGELOG.txt

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Delete existing tag if present
        run: |
          git tag -d ${{ env.RELEASE_VERSION }} || true
          git push origin :refs/tags/${{ env.RELEASE_VERSION }} || true
        continue-on-error: true

      - name: Create and push new tag
        run: |
          git tag ${{ env.RELEASE_VERSION }}
          git push origin ${{ env.RELEASE_VERSION }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          bodyFile: ${{ github.workspace }}-CHANGELOG.txt
          artifacts: "out/main.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true

      - name: Notify Beta Readers
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://n8n.viz.li/webhook/4cbf803f-42df-4bd1-9eac-898a5435907d'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"releaseURL": "https://github.com/authwit/book-NigerianBizOpsBlueprint/releases/tag/${{ env.RELEASE_VERSION }}", "version" : "${{ env.RELEASE_VERSION }}", "bookURL": "https://raw.githubusercontent.com/authwit/book-NigerianBizOpsBlueprint/blob/main/out/main.pdf" }'